version: '3.5' 

services: 

    frontend: 
      image: frontend
      build: . 
      ports:
        - 5000:5000
      container_name: frontend

    backend: 
      image: backend
      build: . 
      ports:
        - 8000:8000
      environment: 
        - REDIS=redis
      container_name: backend

    redis:
      image: redis:6.0.8