version: '3.5' 

services: 

    ports_exercise: 
      image: devopsdockeruh/ports_exercise
      build: . 
      ports:
        - 80:80
      volumes: 
        - .:/mydir
      container_name: ports_exercise