version: '3.5' 

services: 

    frontend: 
      image: frontend
      build: . 
      ports:
        - 5000:5000
      container_name: frontend

    backend: 
      image: backend
      build: . 
      ports:
        - 8000:8000
      environment: 
        - REDIS=redis
        - DB_USERNAME=admin
        - DB_PASSWORD=testi
        - DB_HOST=db
      container_name: backend

    redis:
      image: redis:6.0.8

    db:
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=testi
      volumes:
        - database:/var/lib/postgresql/data  
      container_name: db

volumes:
  database: