version: '3.5' 

services: 

    frontend: 
      image: ml-kurkkumopo-frontend
      build: ./ml-kurkkumopo-frontend
      ports:
        - 3000:3000
      container_name: ml-kurkkumopo-frontend

    backend: 
      image: ml-kurkkumopo-backend
      build: ./ml-kurkkumopo-backend
      ports:
        - 5000:5000
      container_name: ml-kurkkumopo-backend
      volumes:
        - /model:/src/model

    training:
      image: ml-kurkkumopo-training
      build: ./ml-kurkkumopo-training
      container_name: ml-kurkkumopo-training
      volumes:
        - /model:/src/model
        - /imgs:/src/imgs